add meraki

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -15,7 +15,6 @@ jobs:
           POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
         ports:
           - 5432:5432
-        
 
     steps:
       - uses: actions/checkout@v3
@@ -34,14 +33,12 @@ jobs:
           SPRING_DATASOURCE_PASSWORD: ${{ secrets.DB_PASSWORD }}
         run: mvn clean package -Dmaven.test.skip=true 
 
-      # 🔐 Login en Docker Hub
       - name: Login to Docker Hub
         uses: docker/login-action@v3
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
 
-      # 🐳 Build & Push imagen
       - name: Build and push Docker image
         uses: docker/build-push-action@v5
         with:
@@ -51,12 +48,16 @@ jobs:
             ${{ secrets.DOCKERHUB_USERNAME }}/mgtapp:latest
             ${{ secrets.DOCKERHUB_USERNAME }}/mgtapp:${{ github.sha }}
 
-      - name: Call Meraki API
+      - name: Validate Meraki Network Exists
         run: |
-          curl -L \
-          -H "X-Cisco-Meraki-API-Key: $MERAKI_API_KEY" \
-          -H "Content-Type: application/json" \
-          -X GET \
-          "https://api.meraki.com/api/v1/organizations/1749173/networks"
+          RESPONSE=$(curl -s -L \
+            -H "X-Cisco-Meraki-API-Key: $MERAKI_API_KEY" \
+            -H "Content-Type: application/json" \
+            -X GET \
+            "https://api.meraki.com/api/v1/organizations/1749173/networks")
+
+          echo "$RESPONSE"
+
+          echo "$RESPONSE" | grep "lab-test" || (echo "Network not found!" && exit 1)
         env:
-          MERAKI_API_KEY: ${{ secrets.MERAKI_API_KEY }}     
+          MERAKI_API_KEY: ${{ secrets.MERAKI_API_KEY }}
